// Generated by gencpp from file ur3_robotics/UR3Joints.msg
// DO NOT EDIT!


#ifndef UR3_ROBOTICS_MESSAGE_UR3JOINTS_H
#define UR3_ROBOTICS_MESSAGE_UR3JOINTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ur3_robotics
{
template <class ContainerAllocator>
struct UR3Joints_
{
  typedef UR3Joints_<ContainerAllocator> Type;

  UR3Joints_()
    : joint_base(0.0)
    , joint_shoulder(0.0)
    , joint_elbow(0.0)
    , joint_wrist1(0.0)
    , joint_wrist2(0.0)
    , joint_wrist3(0.0)  {
    }
  UR3Joints_(const ContainerAllocator& _alloc)
    : joint_base(0.0)
    , joint_shoulder(0.0)
    , joint_elbow(0.0)
    , joint_wrist1(0.0)
    , joint_wrist2(0.0)
    , joint_wrist3(0.0)  {
  (void)_alloc;
    }



   typedef double _joint_base_type;
  _joint_base_type joint_base;

   typedef double _joint_shoulder_type;
  _joint_shoulder_type joint_shoulder;

   typedef double _joint_elbow_type;
  _joint_elbow_type joint_elbow;

   typedef double _joint_wrist1_type;
  _joint_wrist1_type joint_wrist1;

   typedef double _joint_wrist2_type;
  _joint_wrist2_type joint_wrist2;

   typedef double _joint_wrist3_type;
  _joint_wrist3_type joint_wrist3;





  typedef boost::shared_ptr< ::ur3_robotics::UR3Joints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur3_robotics::UR3Joints_<ContainerAllocator> const> ConstPtr;

}; // struct UR3Joints_

typedef ::ur3_robotics::UR3Joints_<std::allocator<void> > UR3Joints;

typedef boost::shared_ptr< ::ur3_robotics::UR3Joints > UR3JointsPtr;
typedef boost::shared_ptr< ::ur3_robotics::UR3Joints const> UR3JointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur3_robotics::UR3Joints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur3_robotics::UR3Joints_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ur3_robotics

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ur3_robotics': ['/home/ialab2020/Desktop/ros_ur3_unity_vr/src/ur3_robotics/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ur3_robotics::UR3Joints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur3_robotics::UR3Joints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur3_robotics::UR3Joints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur3_robotics::UR3Joints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur3_robotics::UR3Joints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur3_robotics::UR3Joints_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur3_robotics::UR3Joints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5ff4378c889479c886a29cb017cf9cde";
  }

  static const char* value(const ::ur3_robotics::UR3Joints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5ff4378c889479c8ULL;
  static const uint64_t static_value2 = 0x86a29cb017cf9cdeULL;
};

template<class ContainerAllocator>
struct DataType< ::ur3_robotics::UR3Joints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur3_robotics/UR3Joints";
  }

  static const char* value(const ::ur3_robotics::UR3Joints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur3_robotics::UR3Joints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 joint_base\n\
float64 joint_shoulder\n\
float64 joint_elbow\n\
float64 joint_wrist1\n\
float64 joint_wrist2\n\
float64 joint_wrist3\n\
\n\
";
  }

  static const char* value(const ::ur3_robotics::UR3Joints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur3_robotics::UR3Joints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_base);
      stream.next(m.joint_shoulder);
      stream.next(m.joint_elbow);
      stream.next(m.joint_wrist1);
      stream.next(m.joint_wrist2);
      stream.next(m.joint_wrist3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UR3Joints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur3_robotics::UR3Joints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur3_robotics::UR3Joints_<ContainerAllocator>& v)
  {
    s << indent << "joint_base: ";
    Printer<double>::stream(s, indent + "  ", v.joint_base);
    s << indent << "joint_shoulder: ";
    Printer<double>::stream(s, indent + "  ", v.joint_shoulder);
    s << indent << "joint_elbow: ";
    Printer<double>::stream(s, indent + "  ", v.joint_elbow);
    s << indent << "joint_wrist1: ";
    Printer<double>::stream(s, indent + "  ", v.joint_wrist1);
    s << indent << "joint_wrist2: ";
    Printer<double>::stream(s, indent + "  ", v.joint_wrist2);
    s << indent << "joint_wrist3: ";
    Printer<double>::stream(s, indent + "  ", v.joint_wrist3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR3_ROBOTICS_MESSAGE_UR3JOINTS_H
