// Generated by gencpp from file ur3_robotics/UR3ServiceMsgRequest.msg
// DO NOT EDIT!


#ifndef UR3_ROBOTICS_MESSAGE_UR3SERVICEMSGREQUEST_H
#define UR3_ROBOTICS_MESSAGE_UR3SERVICEMSGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ur3_robotics/UR3Joints.h>

namespace ur3_robotics
{
template <class ContainerAllocator>
struct UR3ServiceMsgRequest_
{
  typedef UR3ServiceMsgRequest_<ContainerAllocator> Type;

  UR3ServiceMsgRequest_()
    : joint_input()  {
    }
  UR3ServiceMsgRequest_(const ContainerAllocator& _alloc)
    : joint_input(_alloc)  {
  (void)_alloc;
    }



   typedef  ::ur3_robotics::UR3Joints_<ContainerAllocator>  _joint_input_type;
  _joint_input_type joint_input;





  typedef boost::shared_ptr< ::ur3_robotics::UR3ServiceMsgRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur3_robotics::UR3ServiceMsgRequest_<ContainerAllocator> const> ConstPtr;

}; // struct UR3ServiceMsgRequest_

typedef ::ur3_robotics::UR3ServiceMsgRequest_<std::allocator<void> > UR3ServiceMsgRequest;

typedef boost::shared_ptr< ::ur3_robotics::UR3ServiceMsgRequest > UR3ServiceMsgRequestPtr;
typedef boost::shared_ptr< ::ur3_robotics::UR3ServiceMsgRequest const> UR3ServiceMsgRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur3_robotics::UR3ServiceMsgRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur3_robotics::UR3ServiceMsgRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ur3_robotics

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ur3_robotics': ['/home/ialab2020/Desktop/ros_ur3_unity_vr/src/ur3_robotics/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ur3_robotics::UR3ServiceMsgRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur3_robotics::UR3ServiceMsgRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur3_robotics::UR3ServiceMsgRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur3_robotics::UR3ServiceMsgRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur3_robotics::UR3ServiceMsgRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur3_robotics::UR3ServiceMsgRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur3_robotics::UR3ServiceMsgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "96b86e5a23687685361fc807179e53a0";
  }

  static const char* value(const ::ur3_robotics::UR3ServiceMsgRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x96b86e5a23687685ULL;
  static const uint64_t static_value2 = 0x361fc807179e53a0ULL;
};

template<class ContainerAllocator>
struct DataType< ::ur3_robotics::UR3ServiceMsgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur3_robotics/UR3ServiceMsgRequest";
  }

  static const char* value(const ::ur3_robotics::UR3ServiceMsgRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur3_robotics::UR3ServiceMsgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "UR3Joints joint_input\n\
\n\
================================================================================\n\
MSG: ur3_robotics/UR3Joints\n\
float64 joint_base\n\
float64 joint_shoulder\n\
float64 joint_elbow\n\
float64 joint_wrist1\n\
float64 joint_wrist2\n\
float64 joint_wrist3\n\
\n\
";
  }

  static const char* value(const ::ur3_robotics::UR3ServiceMsgRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur3_robotics::UR3ServiceMsgRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UR3ServiceMsgRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur3_robotics::UR3ServiceMsgRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur3_robotics::UR3ServiceMsgRequest_<ContainerAllocator>& v)
  {
    s << indent << "joint_input: ";
    s << std::endl;
    Printer< ::ur3_robotics::UR3Joints_<ContainerAllocator> >::stream(s, indent + "  ", v.joint_input);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR3_ROBOTICS_MESSAGE_UR3SERVICEMSGREQUEST_H
