// Generated by gencpp from file ros_tcp_endpoint/UnityHandshakeRequest.msg
// DO NOT EDIT!


#ifndef ROS_TCP_ENDPOINT_MESSAGE_UNITYHANDSHAKEREQUEST_H
#define ROS_TCP_ENDPOINT_MESSAGE_UNITYHANDSHAKEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_tcp_endpoint
{
template <class ContainerAllocator>
struct UnityHandshakeRequest_
{
  typedef UnityHandshakeRequest_<ContainerAllocator> Type;

  UnityHandshakeRequest_()
    : ip()
    , port(0)  {
    }
  UnityHandshakeRequest_(const ContainerAllocator& _alloc)
    : ip(_alloc)
    , port(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _ip_type;
  _ip_type ip;

   typedef uint16_t _port_type;
  _port_type port;





  typedef boost::shared_ptr< ::ros_tcp_endpoint::UnityHandshakeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_tcp_endpoint::UnityHandshakeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct UnityHandshakeRequest_

typedef ::ros_tcp_endpoint::UnityHandshakeRequest_<std::allocator<void> > UnityHandshakeRequest;

typedef boost::shared_ptr< ::ros_tcp_endpoint::UnityHandshakeRequest > UnityHandshakeRequestPtr;
typedef boost::shared_ptr< ::ros_tcp_endpoint::UnityHandshakeRequest const> UnityHandshakeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_tcp_endpoint::UnityHandshakeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_tcp_endpoint::UnityHandshakeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_tcp_endpoint

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ros_tcp_endpoint': ['/home/ialab2020/Desktop/ros_ur3_unity_vr/src/ros_tcp_endpoint/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_tcp_endpoint::UnityHandshakeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_tcp_endpoint::UnityHandshakeRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_tcp_endpoint::UnityHandshakeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_tcp_endpoint::UnityHandshakeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_tcp_endpoint::UnityHandshakeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_tcp_endpoint::UnityHandshakeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_tcp_endpoint::UnityHandshakeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0d7108a8353c437472bddab9a8d6708e";
  }

  static const char* value(const ::ros_tcp_endpoint::UnityHandshakeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0d7108a8353c4374ULL;
  static const uint64_t static_value2 = 0x72bddab9a8d6708eULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_tcp_endpoint::UnityHandshakeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_tcp_endpoint/UnityHandshakeRequest";
  }

  static const char* value(const ::ros_tcp_endpoint::UnityHandshakeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_tcp_endpoint::UnityHandshakeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string ip\n\
uint16 port\n\
";
  }

  static const char* value(const ::ros_tcp_endpoint::UnityHandshakeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_tcp_endpoint::UnityHandshakeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ip);
      stream.next(m.port);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UnityHandshakeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_tcp_endpoint::UnityHandshakeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_tcp_endpoint::UnityHandshakeRequest_<ContainerAllocator>& v)
  {
    s << indent << "ip: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.ip);
    s << indent << "port: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.port);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_TCP_ENDPOINT_MESSAGE_UNITYHANDSHAKEREQUEST_H
